# Generated by Django 6.0.5 on 2026-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionhero",
            name="button_text",
        ),
        migrations.RemoveField(
            model_name="admissionhero",
            name="image",
        ),
    ]
