# Generated by Django 6.0.7 on 2026-07-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Campus', 'Campus'), ('Classrooms', 'Classrooms'), ('Laboratories', 'Laboratories'), ('Sports', 'Sports'), ('Events', 'Events'), ('Transport', 'Transport'), ('Hostel', 'Hostel'), ('Activities', 'Activities'), ('Other', 'Other')], default='Campus', max_length=50)),
                ('image', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
