# Generated by Django 6.0.7 on 2026-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('National', 'National'), ('Festival', 'Festival'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('image', models.ImageField(upload_to='events')),
                ('is_upcoming', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
