# Generated by Django 6.0.7 on 2026-07-13 11:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hostelroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
