# Generated by Django 6.0.7 on 2026-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
